### ISSUE TITLE
Feature request: make "Clarity" property a Graph curve

### ISSUE THREAD

**Issue by golddotasksquestions** [Arnklit/WaterGenGodot#2]
Depending on how murky a river is, if it is magical or realistic natural, fast or slow moving ... the falloff of the clarity property would be great if adjustable and not linear.
https://youtu.be/gHT3jsCEiyA?t=183

**Comment by Arnklit** [comment]
Added in 0.2.1 which is now released:

![z8GimZgFoz](https://user-images.githubusercontent.com/4955051/105999340-7690bf00-60a5-11eb-8aac-84fc579b8bf4.gif)
