### ISSUE TITLE
Unable to enable this Addon in "Godot v4.2.2".

### ISSUE THREAD

**Issue by vishalbandre** [Arnklit/WaterGenGodot#26]
**Describe the bug**
This addon is not working in "Godot v4.2.2".

Unable to enable "Waterways" addon. Getting error at Project -> Project Settings -> Plugins -> Waterways.

**To Reproduce**
1. Go to 'Project -> Project Settings -> Plugins'
2. Click on 'Enable' for this addons' status.
3. See error
**Error:**
"Unable to load addon script from path: 'res://addons/waterways/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/waterways/plugin.cfg' to prevent further errors."

Console Dump:
"  res://addons/waterways/plugin.gd:3 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://addons/waterways/plugin.gd" with error "Parse error". (User)"

**Expected behavior**
Enable addon without any error.

**Screenshots**
![Screenshot from 2024-04-20 09-39-32](https://github.com/Arnklit/Waterways/assets/2410377/0837508a-e99e-410e-9500-6e006d4185a8)

**Environment**
- OS: Ubuntu 22.04.4 LTS
- Graphics card: Vulkan (Mobile) - integrated Intel(R) Xe Graphics (TGL GT2)
- Godot version: 4.2.2
- Plugin version: v0.2.1
- Renderer used: Mobile

**Comment by TokisanGames** [comment]
The main branch of the plugin isn't compatible with any Godot 4 version.
You can try the 4.0 branch and look through the issues for patches that will get it working.

**Comment by vishalbandre** [comment]
Thanks for the update. v4 branch works well with Godot v4.2.2.
