### ISSUE TITLE
Rename suggestion: Rename "Normal Scale" to "Normal depth" and "Tiling" to "Texture scale"

### ISSUE THREAD

**Issue by golddotasksquestions** [Arnklit/WaterGenGodot#3]
It took me a long time to figure out that "Tiling" was related to what I would usually assume as a scale. For the longest while I thought there is only "Normal Scale", to adjust the normal depth vertically , but no way to scale the Texture horizontally. The I only kept searching for a propery was because I had the faint memory of seeing a video of you demonstrating horizontal texture scaling.

**Comment by Arnklit** [comment]
Changed Tiling to UV Scale and turned it into a vector for more control. I prefer keeping Normal Scale as that is the standard in Godot shaders elsewhere.

![Godot_v3 2 3-stable_win64_2TLkfO0qEz](https://user-images.githubusercontent.com/4955051/102809932-bedc0380-43ba-11eb-8600-88fbed0d6276.png)

**Comment by Arnklit** [comment]
Closing, this is in master if you want to test.
