### ISSUE TITLE
Issue with transparent objects

### ISSUE THREAD

**Issue by Mercadud** [Arnklit/WaterGenGodot#9]
**Describe the bug**
Inability to see transparent objects in front of Water/Lava

**To Reproduce**
Steps to reproduce the behaviour:
1. create an object with the transparent flag checked
2. add the river node behind and make it whatever shape you want
3. in-game the parts of the transparent mesh that are in front of the river doesn't seem to be visible, but the rest should be fine

**Expected behaviour**
the transparent mesh is supposed to show as expected, transparent

**Screenshots**
expected (view from editor):
![image](https://user-images.githubusercontent.com/34464977/106485756-effe2800-647e-11eb-8211-897a8329411b.png)
current issue (in-game):
![image](https://user-images.githubusercontent.com/34464977/106485924-1ae87c00-647f-11eb-8ae7-433dcd988204.png)

**Environment**
- OS: Manjaro
- Graphics card: RX 5700xt
- Godot version 3.2.3
- Plugin version 0.2.1
- Renderer used GLES 3

thanks in advance

**Comment by Mercadud** [comment]
update:
I think it depends on which direction you look at the object
it rebecomes visible depending on which angle you look at it. might be because of the surrounding objects tho

**Comment by Arnklit** [comment]
I believe this is as expected. The lava is being rendered as a transparent object, to be able to do depth effects. so if you want transparent objects to display correctly in front of it you'll have to check "Depth Draw Mode -> Opaque Pre-Pass" on the material. Or if it's a custom shader, add the "depth_draw_always" render_mode.

**Comment by Mercadud** [comment]
changing the Depth Draw Mode to Opaque Pre-Pass on the object in front doesn't seem to have the desired effect.

**Comment by Arnklit** [comment]
You might have to set the render priority of your transparent material to something higher that 0 for it to render in front of the lava as well.

**Comment by Mercadud** [comment]
ok perfect that works, for the people that are having the same issue:
1. Depth Draw Mode -> Opaque Pre-Pass
2. make render priority higher than the river
